Repository SWE-574-Spring-2018/LinkyWay, pull requests merged in 2018-04, with the labels that each got.

#72 Feature/twitterapi
  src/main/java/com/linkyway/controller/TweetController.java
  src/main/java/com/linkyway/controller/WikiNodeController.java
  src/main/java/com/linkyway/service/TweetService.java
Labels: backend, priority-medium

#71 Feature/webresources
  pom.xml
  src/main/java/com/linkyway/LinkywayApplication.java
  src/main/java/com/linkyway/WebConfig.java
  src/main/java/com/linkyway/controller/HomeController.java
  src/main/resources/static/img/twitter_logo.png
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
Labels: web

#78 Twitter annotation template completed.
  src/main/resources/static/css/site.css
  src/main/resources/static/img/tweet_loading.gif
  src/main/resources/static/js/index.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/views/annotation_create.html
  src/main/resources/templates/views/error_generic.html
  src/main/resources/templates/views/error_not_found.html
Labels: backend, frontend, requirement, web

#79 Incorrect thymeleaf tag fixed in home.html
  src/main/resources/templates/views/home.html
Labels: bug, frontend, priority-high

#85 Feature wikiitem
  src/main/java/com/linkyway/controller/service/WikiNodeController.java
  src/main/java/com/linkyway/controller/service/WikidataItemController.java
  src/main/java/com/linkyway/model/entity/WikidataItem.java
  src/main/java/com/linkyway/service/WikidataItemService.java
Labels: backend, priority-high

#84 BE 115 Get TweetNode Completed
  src/main/java/com/linkyway/service/NodeService.java
Labels: backend, priority-high

#88 Feature/twitter node
  src/main/java/com/linkyway/controller/service/NodeController.java
  src/main/java/com/linkyway/service/NodeService.java
Labels: backend, priority-low

#89 Feature/twitter node
  src/main/java/com/linkyway/controller/service/NodeController.java
  src/main/java/com/linkyway/model/domain/Link.java
  src/main/java/com/linkyway/model/domain/RelationshipMap.java
  src/main/java/com/linkyway/repository/NodeRepository.java
  src/main/java/com/linkyway/service/NodeService.java
Labels: backend, priority-high
