Repository SWE-574-Spring-2018/LinkyWay, pull requests merged in 2018-03, with the labels that each got.

#34 Backend Application Setup
  .gitignore
  pom.xml
  src/main/java/com/linkyway/Dao/BaseDao.java
  src/main/java/com/linkyway/Dao/NodeDao.java
  src/main/java/com/linkyway/LinkywayApplication.java
  src/main/java/com/linkyway/controller/NodeController.java
  src/main/java/com/linkyway/controller/RelationController.java
  src/main/java/com/linkyway/domain/Node.java
  src/main/java/com/linkyway/domain/Relation.java
  src/main/java/com/linkyway/domain/RelationType.java
  src/main/java/com/linkyway/entity/AbstractEntity.java
  src/main/java/com/linkyway/entity/NodeEntity.java
  src/main/java/com/linkyway/mapper/NodeEntityMapper.java
  src/main/java/com/linkyway/service/NodeService.java
  src/main/java/com/linkyway/service/RelationService.java
  src/main/resources/application.properties
  src/test/java/com/linkyway/LinkywayApplicationTests.java
Labels: backend, priority-medium

#35 Rebase branch feature/ci_integration
  .gitignore
  pom.xml
  src/main/java/com/linkyway/Dao/BaseDao.java
  src/main/java/com/linkyway/Dao/NodeDao.java
  src/main/java/com/linkyway/LinkywayApplication.java
  src/main/java/com/linkyway/controller/NodeController.java
  src/main/java/com/linkyway/controller/RelationController.java
  src/main/java/com/linkyway/domain/Node.java
  src/main/java/com/linkyway/domain/Relation.java
  src/main/java/com/linkyway/domain/RelationType.java
  src/main/java/com/linkyway/entity/AbstractEntity.java
  src/main/java/com/linkyway/entity/NodeEntity.java
  src/main/java/com/linkyway/mapper/NodeEntityMapper.java
  src/main/java/com/linkyway/service/NodeService.java
  src/main/java/com/linkyway/service/RelationService.java
  src/main/resources/application.properties
  src/test/java/com/linkyway/LinkywayApplicationTests.java
Labels: backend, priority-medium

#31 Added first version of Travis CI configuration file
  .travis.yml
  README.md
Labels: backend, management, priority-medium

#44 Neo4j Integration - Node and relationship structure is implemented
  pom.xml
  src/main/java/com/linkyway/Dao/BaseDao.java
  src/main/java/com/linkyway/Dao/NodeDao.java
  src/main/java/com/linkyway/LinkywayApplication.java
  src/main/java/com/linkyway/controller/NodeController.java
  src/main/java/com/linkyway/controller/RelationController.java
  src/main/java/com/linkyway/controller/RelationshipController.java
  src/main/java/com/linkyway/domain/Node.java
  src/main/java/com/linkyway/domain/Relation.java
  src/main/java/com/linkyway/domain/RelationType.java
  src/main/java/com/linkyway/domain/Relationship.java
  src/main/java/com/linkyway/domain/RelationshipType.java
  src/main/java/com/linkyway/entity/Node.java
  src/main/java/com/linkyway/entity/Relationship.java
  src/main/java/com/linkyway/exception/NoMatchingNodeFoundException.java
  src/main/java/com/linkyway/exception/NodeAlreadyExistsException.java
  src/main/java/com/linkyway/mapper/NodeEntityMapper.java
  src/main/java/com/linkyway/mapper/RelationshipEntityMapper.java
  src/main/java/com/linkyway/repository/NodeRepository.java
  src/main/java/com/linkyway/repository/RelationshipRepository.java
  src/main/java/com/linkyway/service/NodeService.java
  src/main/java/com/linkyway/service/RelationService.java
  src/main/java/com/linkyway/service/RelationshipService.java
  src/main/resources/application.properties
Labels: backend, enhancement

#66 BE-107,BE-108 - implemented twitter login & node display & exception handling
  pom.xml
  src/main/java/com/linkyway/LinkywayApplication.java
  src/main/java/com/linkyway/controller/BaseController.java
  src/main/java/com/linkyway/controller/CustomConnectController.java
  src/main/java/com/linkyway/controller/CustomErrorController.java
  src/main/java/com/linkyway/controller/ErrorControllerAdvice.java
  src/main/java/com/linkyway/controller/HomeController.java
  src/main/java/com/linkyway/controller/LoginController.java
  src/main/java/com/linkyway/controller/NodeController.java
  src/main/java/com/linkyway/controller/RelationshipController.java
  src/main/java/com/linkyway/dao/BaseDao.java
  src/main/java/com/linkyway/dao/ProfileDao.java
  src/main/java/com/linkyway/domain/UserProfile.java
  src/main/java/com/linkyway/entity/User.java
  src/main/java/com/linkyway/mapper/NodeEntityMapper.java
  src/main/java/com/linkyway/mapper/ProfileEntityMapper.java
  src/main/java/com/linkyway/repository/NodeRepository.java
  src/main/java/com/linkyway/service/NodeService.java
  src/main/java/com/linkyway/service/ProfileService.java
  src/main/resources/application.properties
  src/main/resources/templates/errorGeneric.html
  src/main/resources/templates/errorNotFound.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
Labels: backend, priority-medium

#67 WebUI implementation
  demo/annotator/libraries.txt
  demo/home.html
  src/main/Heath_Ledger_tweet_3.PNG
  src/main/java/com/linkyway/WebConfig.java
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/site.css
  src/main/resources/static/fonts/SaturaTextPro.otf
  src/main/resources/static/fonts/SaturaTextPro.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/img/banner/annotation_book_1.jpg
  src/main/resources/static/img/banner/annotation_book_2.jpg
  src/main/resources/static/img/banner/annotation_book_3.jpg
  src/main/resources/static/img/bx_loader.gif
  src/main/resources/static/img/controls.png
  src/main/resources/static/img/logo.png
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/jquery-1.10.2.js
  src/main/resources/static/js/modernizr-2.6.2.js
  src/main/resources/static/js/respond.js
  src/main/resources/static/test.js
  src/main/resources/templates/about.html
  src/main/resources/templates/contact.html
  src/main/resources/templates/create_annotation.html
  src/main/resources/templates/create_node.html
  src/main/resources/templates/create_relation.html
  src/main/resources/templates/demo.html
  src/main/resources/templates/discover_annotations.html
  src/main/resources/templates/discover_nodes.html
  src/main/resources/templates/discover_relations.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/master.html
Labels: design, web
